services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: |
      # Add Swap Memory
      fallocate -l 4G /tmp/swapfile
      chmod 600 /tmp/swapfile
      mkswap /tmp/swapfile
      swapon /tmp/swapfile

      # Install Chromium
      apt-get update && apt-get install -y chromium-browser

      # Set environment variable to ensure Puppeteer downloads Chromium
      export PUPPETEER_SKIP_DOWNLOAD=false

      # Install project dependencies
      yarn install

      # Set Puppeteer executable path to installed Chromium
      export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

      # Remove Swap Memory after installation
      swapoff /tmp/swapfile
      rm /tmp/swapfile
    startCommand: yarn start
